---
  - name: Check for .ssh folder in iCloud drive
    stat:
      path: "~/Library/Mobile Documents/com~apple~CloudDocs/.ssh"
    register: ssh_cloud_path

  - name: Check for .ssh folder in home directory
    stat:
      path: "~/.ssh"
    register: ssh_home_path

  - name: Symlink .ssh folder with the one in iCloud drive
    file:
      path: ~/.ssh
      src: "~/Library/Mobile Documents/com~apple~CloudDocs/.ssh"
      state: link
      mode: 700
    when: ssh_cloud_path.stat.exists == True and ssh_home_path.stat.exists == False

  - name: Fix permissions
    command: "find ~/.ssh -type f -not -name '*.pub' -exec chmod 600 {} \\;"
    when: ssh_cloud_path.stat.exists == True and ssh_home_path.stat.exists == False
