---
  - name: Install GIT
    homebrew:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
    with_items:
      - git
      - git-flow

  - name: Set .gitconfig file
    template:
      src: gitconfig.j2
      dest: ~/.gitconfig

  - name: Set .gitignore file
    template:
      src: gitignore.j2
      dest: "{{ git_config.core.excludesfile }}"
    when: git_ignore and git_config.core is defined and git_config.core.excludesfile is defined
