---
  - name: Download Atom
    get_url:
      url: https://atom.io/download/mac
      dest: /tmp/atom.zip

  - name: Install Atom
    shell: "unzip /tmp/atom.zip -d /Applications"

  - name: Install Atom command
    file:
      src: /Applications/Atom.app/Contents/Resources/app/atom.sh
      dest: /usr/local/bin/atom
      state: link

  - name: Install APM command
    file:
      src: /Applications/Atom.app/Contents/Resources/app/apm/bin/apm
      dest: /usr/local/bin/apm
      state: link

  - name: Install Atom packages
    shell: "/usr/local/bin/apm install {{ item }}"
    with_items: atom_packages
