---
- name: Copy terminal settings file
  copy: src={{ terminal_theme }}.terminal dest=/tmp/{{ terminal_theme }}.terminal

- name: Load terminal theme
  command: open /tmp/{{ terminal_theme }}.terminal
  ignore_errors: yes

- name: Set default terminal theme
  shell: "{{ item }}"
  with_items:
    - 'defaults write com.apple.Terminal "Startup Window Settings" -string {{ terminal_theme }}'
    - 'defaults write com.apple.Terminal "Default Window Settings" -string {{ terminal_theme }}'
